import { describe, expect, test } from "vitest";
import {
  MAX_ICON_SVG_BYTES,
  sanitizeIconSvg,
  svgDataUrl,
} from "./lib/svg";

const NS = 'xmlns="http://www.w3.org/2000/svg"';

function accept(svg: string): string {
  const result = sanitizeIconSvg(svg);
  if (!result.ok) {
    throw new Error(`refused: ${result.error}`);
  }
  return result.svg;
}

function reject(svg: string): string {
  const result = sanitizeIconSvg(svg);
  if (result.ok) {
    throw new Error("accepted, but should have been refused");
  }
  return result.error;
}

describe("what an icon may be", () => {
  test("a plain exported icon passes through unchanged", () => {
    const svg = `<svg ${NS} viewBox="0 0 24 24" fill="none"><path d="M4 4h16v16H4z" fill="#4F46E5" stroke-width="1.5"/></svg>`;
    expect(accept(svg)).toBe(svg);
  });

  test("gradients, clip paths and local references are kept", () => {
    const svg = `<svg ${NS} viewBox="0 0 24 24"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fff" stop-opacity="0.5"/><stop offset="1" stop-color="#000"/></linearGradient><clipPath id="c"><rect width="24" height="24" rx="4"/></clipPath></defs><g clip-path="url(#c)"><circle cx="12" cy="12" r="10" fill="url(#g)"/><use href="#c"/></g></svg>`;
    expect(accept(svg)).toBe(svg);
  });

  test("the metadata drawing programs sprinkle over an export is inert, not refused", () => {
    const svg = `<svg ${NS} viewBox="0 0 24 24" aria-hidden="true" role="img" data-name="Vrstva 1" xml:space="preserve"><title>Logo</title><rect class="cls-1" width="24" height="24"/></svg>`;
    expect(accept(svg)).toBe(svg);
  });

  test("a stylesheet is allowed while it only paints", () => {
    const svg = `<svg ${NS} viewBox="0 0 24 24"><style>.cls-1{fill:#4F46E5;stroke:url(#g)}</style><rect class="cls-1" width="24" height="24"/></svg>`;
    expect(accept(svg)).toBe(svg);
  });

  test("a child combinator is CSS, not corruption", () => {
    const svg = `<svg ${NS} viewBox="0 0 24 24"><style>g > .cls-1{fill:#000}</style><g><rect class="cls-1" width="24" height="24"/></g></svg>`;
    expect(accept(svg)).toBe(svg);
  });

  test("the XML declaration and comments are dropped", () => {
    const cleaned = accept(
      `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generator: Illustrator --><svg ${NS} viewBox="0 0 24 24"><!-- shape --><rect width="24" height="24"/></svg>`,
    );
    expect(cleaned.startsWith("<svg")).toBe(true);
    expect(cleaned).not.toContain("<!--");
    expect(cleaned).not.toContain("<?xml");
  });

  test("a licence comment above the root, and attributes broken over lines", () => {
    const svg = accept(
      `<!--\n  Generated by hand.\n-->\n<svg ${NS} viewBox="0 0 64 64" width="64" height="64">\n  <rect width="64" height="64" rx="14.5" fill="#4F46E5" />\n  <path\n    d="M13 19 H20.5 Z"\n    fill="#ffffff"\n    stroke-linejoin="round"\n  />\n</svg>`,
    );
    expect(svg.startsWith("<svg")).toBe(true);
    expect(svg.endsWith("</svg>")).toBe(true);
  });

  test("a missing namespace is added — without it nothing renders in an <img>", () => {
    const cleaned = accept('<svg viewBox="0 0 24 24"><rect width="24" height="24"/></svg>');
    expect(cleaned).toBe(
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect width="24" height="24"/></svg>',
    );
  });
});

describe("what an icon may never be", () => {
  test("a script element", () => {
    expect(reject(`<svg ${NS}><script>alert(1)</script></svg>`)).toMatch(
      /nepovolený prvek <script>/,
    );
  });

  test("an event handler, whatever its casing", () => {
    expect(reject(`<svg ${NS}><rect onload="alert(1)" width="1" height="1"/></svg>`)).toMatch(
      /obslužný skript onload/,
    );
    expect(reject(`<svg ${NS}><rect OnLoad="alert(1)" width="1" height="1"/></svg>`)).toMatch(
      /obslužný skript OnLoad/,
    );
    expect(reject(`<svg ${NS} onload="alert(1)"></svg>`)).toMatch(/obslužný skript/);
  });

  test("a link out of the document", () => {
    expect(reject(`<svg ${NS}><a href="https://example.com"><rect width="1" height="1"/></a></svg>`)).toMatch(
      /nepovolený prvek <a>/,
    );
    expect(reject(`<svg ${NS}><use href="https://example.com/x.svg#a"/></svg>`)).toMatch(
      /odkazuje mimo sebe/,
    );
    expect(reject(`<svg ${NS}><use xlink:href="//example.com/x.svg#a"/></svg>`)).toMatch(
      /odkazuje mimo sebe/,
    );
  });

  test("anything that loads: images, fonts, embedded documents", () => {
    expect(reject(`<svg ${NS}><image href="https://example.com/x.png"/></svg>`)).toMatch(
      /nepovolený prvek <image>/,
    );
    expect(reject(`<svg ${NS}><foreignObject><div/></foreignObject></svg>`)).toMatch(
      /nepovolený prvek <foreignObject>/,
    );
    expect(reject(`<svg ${NS}><style>@import url(https://example.com/x.css)</style></svg>`)).toMatch(
      /skript nebo vložený obsah/,
    );
    expect(reject(`<svg ${NS}><rect fill="url(https://example.com/x.png)" width="1" height="1"/></svg>`)).toMatch(
      /odkazuje mimo sebe/,
    );
  });

  test("a javascript: or data: URL, however it is spelled", () => {
    expect(reject(`<svg ${NS}><rect fill="javascript:alert(1)" width="1" height="1"/></svg>`)).toMatch(
      /skript nebo vložený obsah/,
    );
    expect(reject(`<svg ${NS}><rect fill="JAVASCRIPT:alert(1)" width="1" height="1"/></svg>`)).toMatch(
      /skript nebo vložený obsah/,
    );
    expect(reject(`<svg ${NS}><rect style="fill:url(data:image/svg+xml,x)" width="1" height="1"/></svg>`)).toMatch(
      /skript nebo vložený obsah/,
    );
  });

  test("a numeric character reference — the place a check like ours is evaded", () => {
    expect(reject(`<svg ${NS}><use href="&#106;avascript:alert(1)"/></svg>`)).toMatch(
      /odkazuje mimo sebe/,
    );
    expect(reject(`<svg ${NS}><rect fill="&#x6a;avascript:alert(1)" width="1" height="1"/></svg>`)).toMatch(
      /nepřečte/,
    );
  });

  test("a doctype, an entity declaration or a CDATA section", () => {
    expect(
      reject(`<!DOCTYPE svg [<!ENTITY x "y">]><svg ${NS}><rect width="1" height="1"/></svg>`),
    ).toMatch(/DOCTYPE nebo sekci CDATA/);
    expect(reject(`<svg ${NS}><style><![CDATA[.a{fill:red}]]></style></svg>`)).toMatch(
      /DOCTYPE nebo sekci CDATA/,
    );
    expect(
      reject(`<svg ${NS}><?xml-stylesheet href="x.css"?><rect width="1" height="1"/></svg>`),
    ).toMatch(/DOCTYPE nebo sekci CDATA/);
  });

  test("an unquoted attribute value — a parser disagreement waiting to happen", () => {
    expect(reject(`<svg ${NS}><rect width=1 height=1/></svg>`)).toMatch(/poškozené/);
  });

  test("markup that does not close, or closes something it did not open", () => {
    expect(reject(`<svg ${NS}><g><rect width="1" height="1"/></svg>`)).toMatch(/poškozené/);
    expect(reject(`<svg ${NS}><rect width="1" height="1"/></g></svg>`)).toMatch(/poškozené/);
    expect(reject(`<svg ${NS}><rect width="1" height="1"`)).toMatch(/poškozené/);
  });

  test("something that is not an SVG at all", () => {
    expect(reject("<html><body>ahoj</body></html>")).toMatch(/není SVG/);
    expect(reject("nazdar")).toMatch(/není SVG/);
    expect(reject("")).toMatch(/není SVG/);
    expect(reject(`<svg xmlns="http://www.w3.org/1999/xhtml"><rect/></svg>`)).toMatch(
      /není SVG/,
    );
  });

  test("a nested <svg>, which reopens the whole question inside itself", () => {
    expect(reject(`<svg ${NS}><svg><rect width="1" height="1"/></svg></svg>`)).toMatch(
      /nepovolený prvek <svg>/,
    );
  });

  test("a NUL byte, which some parsers read as the end of the document", () => {
    expect(reject(`<svg ${NS}>\u0000<rect width="1" height="1"/></svg>`)).toMatch(
      /poškozené/,
    );
  });

  test("more markup than an icon has any use for", () => {
    const huge = `<svg ${NS}>${"<rect width=\"1\" height=\"1\"/>".repeat(2000)}</svg>`;
    expect(huge.length).toBeGreaterThan(MAX_ICON_SVG_BYTES);
    expect(reject(huge)).toMatch(/nejvýš 32 kB/);
  });
});

describe("svgDataUrl", () => {
  test("is a data: URI — no origin, and no page to navigate to", () => {
    const url = svgDataUrl(`<svg ${NS}><rect width="1" height="1"/></svg>`);
    expect(url.startsWith("data:image/svg+xml,")).toBe(true);
    expect(url).not.toContain("<");
    expect(decodeURIComponent(url.slice("data:image/svg+xml,".length))).toContain(
      "<rect",
    );
  });
});
